version: '3.8'

services:
  pharmacy-elasticsearch:
    image: elasticsearch:8.19.3
    container_name: pharmacy-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - pharmacy_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - pharmacy-network
    restart: unless-stopped

  pharmacy-logstash:
    image: logstash:8.19.3
    container_name: pharmacy-logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "5044:5044"
    networks:
      - pharmacy-network
    depends_on:
      - pharmacy-elasticsearch
    restart: unless-stopped

  pharmacy-kibana:
    image: kibana:8.19.3
    container_name: pharmacy-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://pharmacy-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      - XPACK_SECURITY_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=changemechangemechangemechangeme
    ports:
      - "5601:5601"
    networks:
      - pharmacy-network
    depends_on:
      - pharmacy-elasticsearch
    restart: unless-stopped

volumes:
  pharmacy_elasticsearch_data:
    driver: local

networks:
  pharmacy-network:
    name: pharmacy-network  
    driver: bridge 